name: Lazy Script(Schedule)

on:
  schedule:
    - cron: '02 0/1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run app
        run: npm install
      - run: node src/app.js
        env:
          NODE_ENV: 'production'
          NOT_RUN: ${{ secrets.NOT_RUN }}

          SEVER_CHAN_KEY: ${{ secrets.SEVER_CHAN_KEY }}

          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}

          JD_FRUIT_WATER_TIMES: ${{ secrets.JD_FRUIT_WATER_TIMES }}
          JD_FRUIT_SHARE_CODE: ${{ secrets.JD_FRUIT_SHARE_CODE }}
          JD_FRUIT_DUAL_SHARE_CODE: ${{ secrets.JD_FRUIT_DUAL_SHARE_CODE }}
          JD_FRUIT_SHARE_CODE_2: ${{ secrets.JD_FRUIT_SHARE_CODE_2 }}
          JD_FRUIT_SHARE_CODE_3: ${{ secrets.JD_FRUIT_SHARE_CODE_3 }}

          JD_PET_SHARE_CODE: ${{ secrets.JD_PET_SHARE_CODE }}
          JD_PET_DUAL_SHARE_CODE: ${{ secrets.JD_PET_DUAL_SHARE_CODE }}
          JD_PET_SHARE_CODE_1: ${{ secrets.JD_PET_SHARE_CODE_1 }}
          JD_PET_SHARE_CODE_2: ${{ secrets.JD_PET_SHARE_CODE_2 }}
          JD_PET_SHARE_CODE_3: ${{ secrets.JD_PET_SHARE_CODE_3 }}
          JD_PET_SHARE_CODE_4: ${{ secrets.JD_PET_SHARE_CODE_4 }}
          JD_PET_SHARE_CODE_5: ${{ secrets.JD_PET_SHARE_CODE_5 }}
          JD_PET_SHARE_CODE_6: ${{ secrets.JD_PET_SHARE_CODE_6 }}

          JD_CASH_SHARE_CODE: ${{ secrets.JD_CASH_SHARE_CODE }}
          JD_CASH_SHARE_CODE_1: ${{ secrets.JD_CASH_SHARE_CODE_1 }}

          JD_BEAN_SHARE_CODE: ${{ secrets.JD_BEAN_SHARE_CODE }}
          JD_BEAN_SHARE_CODE_1: ${{ secrets.JD_BEAN_SHARE_CODE_1 }}
          JD_BEAN_SHARE_CODE_2: ${{ secrets.JD_BEAN_SHARE_CODE_2 }}
          JD_BEAN_SHARE_CODE_3: ${{ secrets.JD_BEAN_SHARE_CODE_3 }}

          JD_WMT_SHARE_CODE: ${{ secrets.JD_WMT_SHARE_CODE }}
          JD_WMT_SHARE_CODE_1: ${{ secrets.JD_WMT_SHARE_CODE_1 }}

          JD_JDFACTORY_SHARE_CODE: ${{ secrets.JD_JDFACTORY_SHARE_CODE }}
          JD_JDFACTORY_SHARE_CODE_1: ${{ secrets.JD_JDFACTORY_SHARE_CODE_1 }}
          JD_JDFACTORY_SHARE_CODE_2: ${{ secrets.JD_JDFACTORY_SHARE_CODE_2 }}
          JD_JDFACTORY_SHARE_CODE_3: ${{ secrets.JD_JDFACTORY_SHARE_CODE_3 }}

          JD_STALL_SHARE_CODE: ${{ secrets.JD_STALL_SHARE_CODE }}
          JD_STALL_SHARE_CODE_1: ${{ secrets.JD_STALL_SHARE_CODE_1 }}
          JD_STALL_SHARE_CODE_2: ${{ secrets.JD_STALL_SHARE_CODE_2 }}
          JD_STALL_SHARE_CODE_3: ${{ secrets.JD_STALL_SHARE_CODE_3 }}
          JD_STALL_SHARE_CODE_4: ${{ secrets.JD_STALL_SHARE_CODE_4 }}
          JD_STALL_SHARE_CODE_5: ${{ secrets.JD_STALL_SHARE_CODE_5 }}

          JD_STALL_SS: ${{ secrets.JD_STALL_SS }}
          JD_STALL_SS_1: ${{ secrets.JD_STALL_SS_1 }}
          JD_STALL_SS_2: ${{ secrets.JD_STALL_SS_2 }}
          JD_STALL_SS_3: ${{ secrets.JD_STALL_SS_3 }}
          JD_STALL_SS_4: ${{ secrets.JD_STALL_SS_4 }}
          JD_STALL_SS_5: ${{ secrets.JD_STALL_SS_5 }}

          JD_STALL_CRON_SS: ${{ secrets.JD_STALL_CRON_SS }}
          JD_STALL_CRON_SS_1: ${{ secrets.JD_STALL_CRON_SS_1 }}
          JD_STALL_CRON_SS_2: ${{ secrets.JD_STALL_CRON_SS_2 }}
          JD_STALL_CRON_SS_3: ${{ secrets.JD_STALL_CRON_SS_3 }}
          JD_STALL_CRON_SS_4: ${{ secrets.JD_STALL_CRON_SS_4 }}
          JD_STALL_CRON_SS_5: ${{ secrets.JD_STALL_CRON_SS_5 }}
